spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:demo
    username: demo
    password: demo
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html
  mvc:
    view:
      suffix: .html


mybatis:
  type-aliases-package: com.archives.*.model
  mapper-locations: mapper/*.xml

pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mapper:
  mappers:
      - com.archives.foundation.util.UtilMapper
  not-empty: false
  identity: ORACLE





